### PR TITLE
feat: [APP-14459] Upgrade ruby

### PR DESCRIPTION
**Pull request by moorec22**
Jira: https://aurorasolar.atlassian.net/browse/APP-14459

* allow ruby `2.7`, `3.0`, `3.1`
* disallow ruby `2.6`
* upgrade to geometry `1.0.0`

### CODE REVIEW

**Comment by moorec22** [comment]
Is there a way we should be releasing this gem? I don't want to override the previous version

**Review by kpaurora — APPROVED** [review]
Awesome!

**Review by dquimper — APPROVED** [review]
LGTM
What's the sketch project?

**Comment by moorec22** [comment]
@dquimper I believe it's for sketching out geometric shapes. I'm upgrading this for now because the backend at least, on the surface, has files that use it. It may on further investigation no longer be in use.

**Pull request merged**
